name: Build macOS APP
on: [ push ]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'
      - name: Install dependencies
        run: pip install --upgrade pip pyinstaller
      - name: Build .app
        run: pyinstaller --windowed --name Eyetype4You main.py
      - name: Zip .app
        run: zip -r eyetype4you_macos.zip dist/Eyetype4You.app
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eyetype4you_macos
          path: eyetype4you_macos.zip
