name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PyInstaller
        run: pip3 install pyinstaller
      - name: Build .app
        run: |
          pyinstaller --windowed --name Eyetype4You main.py
          cd dist
          zip -r Eyetype4You-macos.zip Eyetype4You.app
      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: dist/Eyetype4You-macos.zip
