name: Build Windows EXE
on: [ push ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: python-version: '3.13.3'
      - name: Install dependencies
        run: pip install --upgrade pip pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile --windowed main.py
      - name: Zip EXE
        run: |
          Compress-Archive -Path dist\main.exe -DestinationPath eyetype4you_windows.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: eyetype4you_windows
          path: eyetype4you_windows.zip
